In [1]:
data = load("dados/dados.RData", verbose=TRUE)

Loading objects:
  inflacao_Y
  RC_
  x
  tab16_9A
  teste_quiquad
  err_pad
  fdamvnorm
  reg_resist
  tab16_5
  age
  tab16_6
  tab16_8
  dados.ex14_6
  moda2
  ano
  mean_sexo
  .First
  mean_idade
  tab6_13
  rbernoulli
  dados.tab4_14
  teste_t
  np_k
  e1
  e2
  MV
  e3
  tab14_10
  p.test
  varp
  q_i
  IC_proporcoes
  moda
  test_tab14_2
  test_tab14_5
  IC_t
  munic
  cd_municipios
  IC
  dados.ex4_4
  scatter.marginal
  c_hum
  dados.ex4_6
  tab4_18
  tab14_2
  tab14_5
  dureza
  dm
  cd_notas
  sex
  tab14_8
  cd_brasil
  c_bio
  n_k
  dados.tab4_7
  dados.tab4_8
  cd_temperaturas
  anos_exp
  IC_t_diff
  scdf
  .Random.seed
  n_clientes
  cd_veiculos
  cd_mercado
  RC
  tab15_1
  tab15_4
  .Last
  tab2_1
  teste_var
  summary2
  acidentes
  cd_poluicao
  IC_diff_medias

In [3]:
cd_brasil

   regiao       uf       superficie pop_urbana pop_rural total    densidade
1  Norte        RO        238513      762864    468143    1231007 5,16
2  Norte        AC        153150      315401    168322     483726 3,16
3  Norte        AM       1577820     1766166    623113    2389279 1,51
4  Norte        RR        225116      174277     72854     247131 1,10
5  Norte        PA       1253165     2949017   2561832    5510849 4,40
6  Norte        AP        143454      330590     48869     379459 2,65
7  Norte        TO        278421      741009    307633    1048642 3,77
8  Nordeste     MA        333366     2711557   2511008    5222565 15,67
9  Nordeste     PI        252379     1556115   1117061    2673176 10,59
10 Nordeste     Litígio*    2977          NA        NA         NA
11 Nordeste     CE        146348     4713311   2096483    6809794 46,53
12 Nordeste     RN         53307     1843486    715174    2558660 48,00
13 Nordeste     PB         56585     2261986   1043630    3305616 58,42
14 Nordeste     PE**       98938     5476915   1922216    7399131 74,79
15 Nordeste     AL         27933     1661914    971425    2633339 94,27
16 Nordeste     SE         22050     1140569    483606    1624175 73,66
17 Nordeste     BA        567295     7826843   4714902   12541745 22,11
18 Sudeste      MG        588384    13074245   3598852   16673097 28,34
19 Sudeste      ES         46184     2176006    626701    2802707 60,69
20 Sudeste      RJ         43910    12806488    599891   13406379 305,32
21 Sudeste      SP        248809    31769219   2351667   34120886 137,14
22 Sul          PR        199709     7011990   1991814    9003804 45,08
23 Sul          SC         95443     3565130   1310114    4875244 51,08
24 Sul          RS        282062     7581230   2056452    9637682 34,17
25 Centro-Oeste MS        358159     1604318    323516    1927834 5,38
26 Centro-Oeste MT        906807     1695548    540284    2235832 2,47
27 Centro-Oeste GO       3412895     3873722    642146    4515868 1323,00
28 Centro-Oeste DF          5822     1692248    129698    1821946 312,94
29              Ilhas***      10          NA        NA         NA